### ISSUE TITLE
TypeError: unhashable type: 'list'  

### ISSUE THREAD

**Issue by VladJamir** [gablg1/ORGAN#14]
I encountered an error
```
Traceback (most recent call last):                                                                                      
File "example.py", line 11, in <module> 
  model.train(ckpt_dir='ckpt')                                                                                        
File "/home/deepest/ORGAN/organ/__init__.py", line 813, in train        
   batch_reward, self.LAMBDA)                                                                                          
File "/home/deepest/ORGAN/organ/rollout.py", line 119, in get_reward                   
   rew = reward_fn(generated_seqs)                                                                                     
File "/home/deepest/ORGAN/organ/__init__.py", line 786, in batch_reward          
   pct_unique = len(list(set(decoded))) / float(len(decoded))                                   
TypeError: unhashable type: 'list' 
```

**Comment by Sphinxs** [comment]
Did you solve this?
