### ISSUE TITLE
Boost.Python.ArgumentError

### ISSUE THREAD

**Issue by mostafachatillon** [gablg1/ORGAN#3]
When running:

`python train_ogan.py exp.json`

I have an error:

`Start pre-training...
  0%|                                                                                                         | 0/240 [00:00<?, ?it/s] gen pre-train
	 test_loss 5.93523359299, train_loss 2.64412474632
/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:2909: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)

Traceback (most recent call last):
  File "train_ogan.py", line 379, in <module>
    main()
  File "train_ogan.py", line 309, in main
    pretrain(sess, generator, target_lstm, train_discriminator)
  File "train_ogan.py", line 193, in pretrain
    mm.compute_results(samples, train_samples, ord_dict, results)
  File "/home/mostafa/Desktop/ORGAN-master/model/mol_metrics.py", line 176, in compute_results
    results[objective] = np.mean(func(verified_samples, train_data))
  File "/home/mostafa/Desktop/ORGAN-master/model/mol_metrics.py", line 231, in batch_diversity
    m, 4, nBits=2048) for m in rand_mols]
Boost.Python.ArgumentError: Python argument types in
    rdkit.Chem.rdMolDescriptors.GetMorganFingerprintAsBitVect(NoneType, int)
did not match C++ signature:
    GetMorganFingerprintAsBitVect(RDKit::ROMol mol, int radius, unsigned int nBits=2048, boost::python::api::object invariants=[], boost::python::api::object fromAtoms=[], bool useChirality=False, bool useBondTypes=True, bool useFeatures=False, boost::python::api::object bitInfo=None)
`

**Comment by mostafachatillon** [comment]
it is an issue with rdkit, see: https://github.com/rdkit/rdkit/issues/1499
